
'use strict';
const names=['初步判断','音色实验','节奏实验','旋律与调式','我是音乐创作者'];
const keys=['旋律','节奏','调式','音色'];
const specs=[['original','原曲主题片段','原作录音 · 教师提供','original.mp3'],['toneA','民族化音色','AI对照素材 · 音色 A','timbre-a.mp3'],['toneB','钢琴、弦乐等西洋音色','AI对照素材 · 音色 B','timbre-b.mp3'],['rhythmA','贴近原作气质的节奏','AI对照素材 · 节奏 A','rhythm-a.mp3'],['rhythmB','现代流行节奏','AI对照素材 · 节奏 B','rhythm-b.mp3']];
const vars=[['速度',['快','慢']],['情绪',['热烈','深情']],['配器',['民族音色','西洋乐器','现代流行音色']],['民族音乐语言',['更多保留','较少保留']]];
let state={page:0,guesses:[],found:[],tone:null,rhythm:null,selection:[null,null,null,null],reveal:false,showcase:false};
try{const s=JSON.parse(sessionStorage.getItem('pamir-class-v1'));if(s&&Array.isArray(s.selection)&&s.selection.length===4)state={...state,...s,page:Math.max(0,Math.min(4,s.page||0))}}catch(e){}
const audio={},urls={},status={};
let playbackIntent=null,playbackVersion=0;
function save(){try{sessionStorage.setItem('pamir-class-v1',JSON.stringify(state))}catch(e){}}
const $=s=>document.querySelector(s);const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
for(const [id,,,file] of specs){let a=new Audio();a.preload='none';a.src='assets/audio/'+file;audio[id]=a;status[id]='待播放';a.addEventListener('playing',()=>{if(playbackIntent!==id){a.pause();return}Object.entries(audio).forEach(([key,other])=>{if(key!==id)other.pause()});status[id]='播放中';updatePlayer(id)});a.addEventListener('pause',()=>{if(!a.ended&&status[id]==='播放中')status[id]='已暂停';updatePlayer(id)});a.addEventListener('ended',()=>{status[id]='播放结束';updatePlayer(id)});a.addEventListener('timeupdate',()=>updatePlayer(id));a.addEventListener('loadedmetadata',()=>updatePlayer(id));a.addEventListener('error',()=>{status[id]='音频未就绪 · 请点右上角“音频准备”';updatePlayer(id)})}
function stopAll(){playbackIntent=null;playbackVersion++;Object.values(audio).forEach(a=>a.pause())}
async function play(id,restart=false){let a=audio[id];if(!restart&&!a.paused){playbackIntent=null;playbackVersion++;a.pause();return}const version=++playbackVersion;playbackIntent=id;Object.entries(audio).forEach(([k,b])=>{if(k!==id)b.pause()});if(restart||a.ended){try{a.currentTime=0}catch(e){}}status[id]='正在加载';updatePlayer(id);try{await a.play()}catch(e){if(version!==playbackVersion)return;status[id]=e.name==='AbortError'?'已暂停':'音频未就绪 · 请点右上角“音频准备”';updatePlayer(id)}}
function clock(t){return Number.isFinite(t)?Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0'):'0:00'}
function updatePlayer(id){let p=document.querySelector('[data-player="'+id+'"]');if(!p)return;let a=audio[id];p.classList.toggle('playing',!a.paused);p.querySelector('.play').textContent=!a.paused?'Ⅱ 暂停':'▶ 播放';p.querySelector('.play').setAttribute('aria-label',specs.find(s=>s[0]===id)[1]+(!a.paused?' 暂停':' 播放'));p.querySelector('.status').textContent=status[id];p.querySelector('.time').textContent=clock(a.currentTime)+' / '+(Number.isFinite(a.duration)?clock(a.duration):'--:--');p.querySelector('.fill').style.width=(a.duration?a.currentTime/a.duration*100:0)+'%'}
function player(id,letter=''){let s=specs.find(x=>x[0]===id);return `<section class="player ${id==='original'?'original':''}" data-player="${id}"><div class="sound-disc" aria-hidden="true"><i></i><b>${letter||'♪'}</b></div><div class="playerTop"><span class="letter">${letter||'♪'}</span><div><h2>${s[1]}</h2><div class="source">${s[2]}</div></div></div><div class="controls"><button class="play primary" data-play="${id}">▶ 播放</button><button class="replay quiet" data-replay="${id}">↺ 重播</button></div><div class="track"><div class="fill"></div></div><div class="metadata"><span class="status" role="status"></span><span class="time"></span></div></section>`}
function heading(n,title,q){return `<div class="heading"><div><p class="eyebrow">${n==='05'?'创作迁移':'帕米尔音乐实验室'} · ${n}</p><h1>${title}</h1><p class="question">${q}</p></div><span class="number">${n}</span></div>`}
function chooseButtons(values,selected,type){return `<div class="choices">${values.map((v,i)=>`<button data-${type}="${i}" aria-pressed="${selected===i}">${selected===i?'✓ ':''}${v}</button>`).join('')}</div>`}
function foundButton(key){return `<button class="discover quiet" data-found="${key}" aria-pressed="${state.found.includes(key)}">${state.found.includes(key)?'✓ 已讨论：':'点亮：'}${key}</button>`}
function render(){save();$('#app').classList.toggle('warm',state.page===4);$('#app').dataset.scene=state.page;$('#nav').innerHTML=names.map((n,i)=>`<button data-page="${i}" ${state.page===i?'aria-current="step"':''}>0${i+1} ${n}</button>`).join('');let h='';
if(state.page===0)h=heading('01','民族味，<br>藏在哪里？','民族味可能藏在哪里？从这一段声音，寻找你的第一感觉。')+`<div class="content">${player('original')}<p class="note">我们的初步猜想 · 可以选择多个要素</p><div class="elements">${keys.map(k=>`<button class="element" data-guess="${k}" aria-pressed="${state.guesses.includes(k)}"><span class="element-icon" aria-hidden="true">${({旋律:"⌁",节奏:"▥",调式:"♮",音色:"◉"})[k]}</span>${k}<small>${state.guesses.includes(k)?'✓ 已记录猜想':'点击记录猜想'}</small></button>`).join('')}</div><div class="live" aria-live="polite">${state.guesses.length?'当前猜想：'+state.guesses.join(' · '):'先听见，再说出你的第一感觉。'}</div></div>`;
if(state.page===1)h=heading('02','只换音色，民族味还在吗？','听听两段音乐，再说说你的判断。')+`<div class="content"><div class="players">${player('toneA','A')}${player('toneB','B')}</div><p class="note">B 相对于 A，民族色彩发生了怎样的变化？</p><div class="judgment">${chooseButtons(['明显增强','明显减弱','基本保留'],state.tone,'tone')}${foundButton('音色')}</div><p class="live">${state.tone===null?'听觉判断由课堂讨论形成。':'已记录学生判断，可继续比较或修改。'}</p></div>`;
if(state.page===2)h=heading('03','节奏变了，感觉怎样？','哪一段更接近《花儿为什么这样红》？')+`<div class="content"><div class="players">${player('rhythmA','A')}${player('rhythmB','B')}</div><p class="note">音乐的气质和民族色彩发生了什么变化？</p><div class="judgment">${chooseButtons(['A 更接近','B 与原作差异更明显'],state.rhythm,'rhythm')}${foundButton('节奏')}</div><p class="live">${state.rhythm===null?'聆听 · 拍击节奏 · 交流感受':'已记录学生判断，可继续比较或修改。'}</p></div>`;
if(state.page===3)h=heading('04','旋律与调式，听见不同。','改动旋律与调式后，你听到了什么变化？')+`<div class="content ${state.reveal?'revealed':''}"><p class="note">现场钢琴示范与讨论后，由教师逐步点亮。</p><div class="relation">${keys.map((k,i)=>(i?'<span class="times">×</span>':'')+`<button class="element ${state.found.includes(k)?'discovered':''}" data-found="${k}" aria-pressed="${state.found.includes(k)}"><span class="element-icon" aria-hidden="true">${({旋律:"⌁",节奏:"▥",调式:"♮",音色:"◉"})[k]}</span>${k}<small>${state.found.includes(k)?'✓ 已讨论':'等待探究'}</small></button>`).join('')}</div><div class="summaryLine"></div><p class="conclusion" aria-live="polite">${state.reveal?'民族音乐风格不是由某一个要素单独决定，而是旋律、节奏、调式、音色等多种音乐语言共同作用的结果。':'先用自己的话，说明这些要素之间的关系。'}</p><div style="text-align:center"><button class="primary" id="reveal" ${state.found.length!==4?'disabled':''}>${state.reveal?'返回归纳前':'归纳完成 · 呈现共同关系'}</button></div></div>`;
if(state.page===4){h=heading('05','我是音乐创作者','如果你得到了一段民族民间音乐素材，现在要用它表现深厚、含蓄的电影人物情感，你会怎样处理？');let s=state.selection,complete=s.every(v=>v!==null);if(state.showcase&&complete){h+=`<div class="content showcase"><p class="eyebrow">小组创作方案</p><div class="hero">${s[0]===0?'快速':'慢速'} × ${vars[1][1][s[1]]}</div><p>${vars[2][1][s[2]]} × ${vars[3][1][s[3]]}民族音乐语言</p><div><button id="edit" class="primary">修改方案</button></div><p class="note">这些选择，将怎样表现人物情感？</p></div>`}else{h+=`<div class="content"><div class="compose"><div>${vars.map(([label,values],i)=>`<div class="variable"><h2>${label}</h2><div class="choices">${values.map((v,j)=>`<button data-variable="${i},${j}" aria-pressed="${s[i]===j}">${s[i]===j?'✓ ':''}${v}</button>`).join('')}</div></div>`).join('')}</div><div class="blueprint" aria-live="polite"><div class="label">把理解变成一次创作选择 · ${s.filter(v=>v!==null).length} / 4</div><h2>小组创作方案</h2><div class="plan-grid">${vars.map(([label,values],i)=>`<div class="plan-item ${s[i]===null?'':'chosen'}"><span>${label}</span><strong>${s[i]===null?'待选择':i===0?(s[i]===0?'快速':'慢速'):values[s[i]]+(i===3?'民族音乐语言':'')}</strong></div>`).join('')}</div><button id="show" class="primary" ${!complete?'disabled':''}>展示完整方案 →</button></div></div></div>`}}
$('#main').innerHTML=h;$('#prev').disabled=state.page===0;$('#next').disabled=state.page===4;for(const [id]of specs)updatePlayer(id)}
function go(p){stopAll();state.page=Math.max(0,Math.min(4,p));render();$('#main').classList.remove('enter');requestAnimationFrame(()=>requestAnimationFrame(()=>$('#main').classList.add('enter')))}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;let d=b.dataset;if(d.page!==undefined)go(Number(d.page));if(d.play)play(d.play);if(d.replay)play(d.replay,true);if(d.guess){let i=state.guesses.indexOf(d.guess);i<0?state.guesses.push(d.guess):state.guesses.splice(i,1);render()}if(d.found){let i=state.found.indexOf(d.found);i<0?state.found.push(d.found):state.found.splice(i,1);if(state.found.length!==4)state.reveal=false;render()}if(d.tone!==undefined){state.tone=Number(d.tone);render()}if(d.rhythm!==undefined){state.rhythm=Number(d.rhythm);render()}if(d.variable){let[i,j]=d.variable.split(',').map(Number);state.selection[i]=j;render()}if(b.id==='reveal'){state.reveal=!state.reveal;render()}if(b.id==='show'){state.showcase=true;render()}if(b.id==='edit'){state.showcase=false;render()}});
$('#prev').onclick=()=>go(state.page-1);$('#next').onclick=()=>go(state.page+1);$('#resources').onclick=()=>{stopAll();$('#settings').showModal()};$('#closeSettings').onclick=()=>$('#settings').close();$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch(e){alert('当前环境不支持全屏，请在电脑浏览器中按 F11。')}};document.addEventListener('fullscreenchange',()=>$('#fullscreen').textContent=document.fullscreenElement?'退出全屏':'全屏');
$('#resourceRows').innerHTML=specs.map(([id,label,,file])=>`<label class="resource"><span>${label}<br><small>${file}</small></span><input type="file" accept="audio/*,.mp3,.wav,.m4a,.ogg" data-file="${id}" aria-label="选择${label}"></label>`).join('');
$('#resourceRows').addEventListener('change',e=>{let id=e.target.dataset.file,f=e.target.files[0];if(!f)return;audio[id].pause();if(urls[id])URL.revokeObjectURL(urls[id]);urls[id]=URL.createObjectURL(f);audio[id].src=urls[id];audio[id].load();status[id]='已选择 · '+f.name;$('#resourceInfo').textContent='已接入：'+f.name;updatePlayer(id)});
$('#reset').onclick=()=>{if(!confirm('清空本轮猜想、讨论标记和创作方案？已选择的音频保留。'))return;stopAll();state={page:0,guesses:[],found:[],tone:null,rhythm:null,selection:[null,null,null,null],reveal:false,showcase:false};render();$('#settings').close()};
window.addEventListener('pagehide',()=>{stopAll();Object.values(urls).forEach(URL.revokeObjectURL)});render();

/* === FIXED-STAGE FITTING & TEACHER NAVIGATION === */
function fitStage(){const scale=Math.min(innerWidth/1920,innerHeight/1080);document.getElementById('app').style.transform=`translate(${(innerWidth-1920*scale)/2}px,${(innerHeight-1080*scale)/2}px) scale(${scale})`;}
fitStage();addEventListener('resize',fitStage);document.getElementById('main').classList.add('enter');
document.addEventListener('keydown',e=>{if(document.getElementById('settings').open||e.target.closest('input,button'))return;if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();go(state.page+1)}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();go(state.page-1)}});
